version: '3.3'

services:
  vote-polsl-server:
    env_file:
      - .env
    container_name: vote-polsl-server
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - '${SERVER_APP_PORT}:8080'
    restart: always
  vote-polsl-client:
    container_name: vote-polsl-client
    build:
      context: client
      dockerfile: ./Dockerfile
      args:
        REACT_APP_SERVER_IP_ADDRESS: ${REACT_APP_SERVER_IP_ADDRESS}
    ports:
      - '${CLIENT_APP_PORT}:80'
    links:
      - vote-polsl-server
    restart: always